name: 'Create a discussion'
description: 'Create a repo discussion on GitHub'
inputs:
  category:
    description: 'Discussion category to create the discussion in'
    required: false
  filename:
    description: 'Filepath to the markdown template for the discussion'
    required: false
  discussion-body:
    description: 'The content of the discussion template as a string'
    required: false
  replacement-text:
    description: 'This text will replace any instances of @PLACEHOLDER_TEXT in the discussion body'
    required: false
  title:
    description: 'Title for the discussion'
    required: true
  title-date:
    description: 'Pass `true` to include the date in the discussion title'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
